apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone
  labels:
    app: netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
      - name: netflix-clone
        image: your-dockerhub-username/netflix-clone:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: netflix-clone-secret
              key: tmdb-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer