name: Deploy Netflix EKS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  EKS_CLUSTER_NAME: netflix-clone-eks
  DOCKER_IMAGE: tektribe/netflix_eks

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        build-args: TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }}

    - name: Deploy
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
        sed -i 's|tektribe/netflix_eks:latest|${{ env.DOCKER_IMAGE }}:${{ github.sha }}|g' k8s/netflix-deployment.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/netflix-deployment.yaml